type StravaActivityResponseDto = {
    resource_state: number;
    athlete: Record<string, unknown>;
    name: string;
    distance: number;
    moving_time: number;
    elapsed_time: number;
    total_elevation_gain: number;
    type: string;
    sport_type: string;
    id: number;
    heartrate: number | undefined;
    start_date: Date;
    start_date_local: Date;
    timezone: string;
    utc_offset: number;
    location_city: string | null;
    location_state: string | null;
    location_country: string;
    achievement_count: number;
    kudos_count: number;
    comment_count: number;
    athlete_count: number;
    photo_count: number;
    map: Record<string, unknown>;
    trainer: boolean;
    commute: boolean;
    manual: boolean;
    private: boolean;
    visibility: string;
    flagged: boolean;
    gear_id: number | null;
    start_latlng: unknown[];
    end_latlng: unknown[];
    average_speed: number;
    max_speed: number;
    has_heartrate: boolean;
    heartrate_opt_out: boolean;
    display_hide_heartrate_option: boolean;
    upload_id: number | null;
    external_id: number | null;
    from_accepted_tag: boolean;
    pr_count: number;
    total_photo_count: number;
    has_kudoed: boolean;
    description: string;
    calories: number;
    perceived_exertion: unknown;
    prefer_perceived_exertion: unknown;
    segment_efforts: unknown[];
    photos: Record<string, unknown>;
    stats_visibility: Record<string, object>[];
    hide_from_home: boolean;
    embed_token: string;
    private_note: string;
    available_zones: unknown[];
};

export { type StravaActivityResponseDto };
