extends:
    - ../.stylelintrc.yml

rules:
    at-rule-no-unknown:
        - true
        - ignoreAtRules:
              - tailwind
              - apply
              - variants
              - responsive
              - screen
