const CM_TO_MM_CONVERSION_FACTOR = 0.1;
const MM_TO_CM_CONVERSION_FACTOR = 10;
const KG_TO_GRAMS_CONVERSION_FACTOR = 1000;
const ROUNDING_FACTOR = 100;

export {
    CM_TO_MM_CONVERSION_FACTOR,
    KG_TO_GRAMS_CONVERSION_FACTOR,
    MM_TO_CM_CONVERSION_FACTOR,
    ROUNDING_FACTOR,
};
