const UserValidationRule = {
    EMAIL: {
        MIN_LENGTH: 6,
        MAX_LENGTH: 320,
        LOCAL_MIN_LENGTH: 1,
        LOCAL_MAX_LENGTH: 64,
        DOMAIN_MIN_LENGTH: 4,
        DOMAIN_MAX_LENGTH: 254,
    },
    PASSWORD: {
        MIN_LENGTH: 6,
        MAX_LENGTH: 12,
    },
    EMAIL_MINIMUM_LENGTH: 1,
    FULLNAME_MINIMUM_LENGTH: 2,
    FULLNAME_MAXIMUM_LENGTH: 60,
    NICKNAME_MINIMUM_LENGTH: 2,
    NICKNAME_MAXIMUM_LENGTH: 30,
    WEIGHT_MINIMUM_LENGTH: 2,
    WEIGHT_MAXIMUM_LENGTH: 20,
    HEIGHT_MINIMUM_LENGTH: 2,
    HEIGHT_MAXIMUM_LENGTH: 20,
} as const;

export { UserValidationRule };
