const IconName = {
    arrowDown: 'arrowDown',
    logoIcon: 'logoIcon',
    notFoundIcon: 'notFoundIcon',
    stravaIcon: 'stravaIcon',
    googleFitIcon: 'googleFitIcon',
    googleLogoIcon: 'googleLogoIcon',
    goalsIcon: 'goalsIcon',
    facebookIcon: 'facebookIcon',
    workoutIcon: 'workoutIcon',
    logoHeader: 'logoHeader',
    logoHeaderLight: 'logoHeaderLight',
    caloriesIcon: 'caloriesIcon',
    stepsIcon: 'stepsIcon',
    cyclingIcon: 'cyclingIcon',
    runningIcon: 'runningIcon',
    walkingIcon: 'walkingIcon',
    bellIcon: 'bellIcon',
    communityIcon: 'communityIcon',
    feedIcon: 'feedIcon',
    goalIcon: 'goalIcon',
    starIcon: 'starIcon',
    searchIcon: 'searchIcon',
} as const;

export { IconName };
